### ISSUE TITLE
x64dbg crash when loaded ERC plugin on windows 7 x64

### ISSUE THREAD

**Issue by houbobhou** [Andy53/ERC.Xdbg#2]
steps to reproduce:
1. extract 2020-11-02_01-33
2. create plugins folder in x32 and x64 folder
3. extract ERC.Xdbg_32-1.3 to x32/plugins folder
4. extract ERC.Xdbg_64-1.3 to x64/plugins folder
5. launch x64dbg 

result:
x64dbg crashed( Stopped working)

remove ERC plugins, x64dbg can launch successfully

this issue can be reproduced on win7 x64, but can not reproduced on win10 x64

**Comment by Andy53** [comment]
Hi,

Do you have .Net Framework 4.7.2 installed? it can be downloaded [here](https://dotnet.microsoft.com/download/dotnet-framework/net472)

**Comment by houbobhou** [comment]
> Hi,
> 
> Do you have .Net Framework 4.7.2 installed? it can be downloaded [here](https://dotnet.microsoft.com/download/dotnet-framework/net472)

thanks for your quick response. 

cool. resolved.
yesterday I tried .net core and .net 4.0 but failed. 


BTW, I love ERC, it's a great plugin.
