### ISSUE TITLE
SearchMemory breaks when null byte added to -Bytes Global Variable

### ISSUE THREAD

**Issue by AndroxNZ** [Andy53/ERC.Xdbg#6]
When the null byte is added to the `-Bytes` global variable, `--SearchMemory` will no longer find any results. 
E.g: `ERC --SearchMemory FF E4 -Bytes 00`
While if I go try `ERC --SearchMemory FF E4 -Bytes` I'll immediately get results, including results with no `00` in the address, which should have been found when `00` was excluded.

Using latest versions of x32dbg and ERC, on a Windows 10 64-bit machine.

**Comment by Andy53** [comment]
I will look into this.

**Comment by Andy53** [comment]
This has been rectified in the latest release.
